### ISSUE TITLE
Doesn't complie

### ISSUE THREAD

**Issue by JeroenWur** [ij96/Honeywell_RSC#3]
Hi, Nice library, but it just doesn't compile. There is no valid conversion for the catalog_listing member function etc.

Honeywell_RSC.h:49:41: error: invalid conversion from 'const unsigned char*' to 'char*' [-fpermissive]
   char* catalog_listing() const {return _catalog_listing;}

**Comment by jvoermans** [comment]
@jerabaul29 Any ideas? I'm encountering the same problem when I 'verify' the arduino sketch. 
It compiles fine on a Mega, but on a Due or Redboard Artemis, I get the error above as well.

With the mega it is a big hassle to test whether the sketch/sensor works, as the sensor voltage is 3-3.6V, then I need to add a few voltage logic/level converter.

**Comment by JeroenWur** [comment]
The DUE has a 3V3 output, so use that for power supply. I have gotten a SSC sensor that has no convertion calculations. The values I did get from this library are totally strange and unusable. 
I removed the 'getters' for string return and only used the 'raw value' getters. That did fix it.

**Comment by jvoermans** [comment]
@jerabaul29 Thanks. Uploaded and connected to the Due. Through the example sketch, I'm getting values now. Changes in readings when adding pressure to one of the nozzles is consistent with expectations.

Only issue is that it won't read the units of pressure from the EEPROM, just comes back as blank.
https://github.com/ij96/Honeywell_RSC/blob/25d3ae0062f9c585adf7aea1dd85f913a5829714/src/Honeywell_RSC.cpp#L123-L153

I checked the datasheet, and something regarding this has been corrected before already, indeed should be length 5:
https://github.com/ij96/Honeywell_RSC/blob/25d3ae0062f9c585adf7aea1dd85f913a5829714/src/rsc_regs.h#L145

Any suggestions how to check this unit issue further?

**Comment by jerabaul29** [comment]
@jvoermans  great, many thanks for the update, excellent to hear that this compiles and provides reasonable results now :) .

Regarding the pressure unit issue:

- what exact code are you running? Can you post 1) the code you are running, 2) the serial output you get?
- I pushed a couple of extra commits to my repo, can you try with this and let me know how things look like?

**Comment by jerabaul29** [comment]
(if you can show me how the prints and in particular the DBG messages look like that would be great :) ).

**Comment by jvoermans** [comment]
@jerabaul29 DBG messages are:

DBG: content of buf from eeprom_read of pressure unit:
DBG 69=105 | 6E=110 | 48=72 | 32=50 | 0=0 | 
DBG: content of _pressure_unit_name: 
DBG 0= | 0= | 0= | 0= | 0= | 0= | 0= | 0= | 0= | 0= | 0= | 0= | 0= | 0= | 0= | 0= | 0= | 0= | 0= | 0= | 0= | 0= | 0= | 0= | 0= | 0= | 0= | 0= | 0= | 0= | 0= | 0= |
DBG: content of buf from eeprom_read of sensor type: 
DBG 44=68 |
DBG: content of _pressure_type_name: 
DBG 64=d | 69=i | 66=f | 66=f | 65=e | 72=r | 65=e | 6E=n | 74=t | 69=i | 61=a | 6C=l | 0= |  0= |  0= |  0= |  0= |  0= |  0= |  0= |  0= |  0= |  0= |  0= |  0= |  0= |  0= |  0= |  0= |  0= |  0= |  0= | 

catalog listing:	82
serial number:		50
pressure range:		4.00
pressure minimum:	-2.00
pressure unit:		
pressure type:		d

**Comment by jerabaul29** [comment]
Can you try again with what I just pushed and show me the full output?

The strings are a bit weirdly handled in this library in my taste (maybe I am just the person who is confused, but to me the strings typing and printing is not done consistently through the library and it is a bit painful as a consequence...).

**Comment by jvoermans** [comment]
See figure attached. I made a print screen this time as 'copy-paste' doesn't work well with this output.
![Picture2](https://user-images.githubusercontent.com/43016672/138180041-894d0848-72fb-45f3-adc5-31e4975afd75.png)

Note that pressure = -0.15 is probs fine, seems like a bias.

**Comment by jerabaul29** [comment]
Ok, thanks, will push agains ina couple of hours :) .

**Comment by jerabaul29** [comment]
@jvoermans you are not using the latest version of the code I pushed :) . I updated (and will still update :) ) both the example .ino and the library :) . Working a bit more on the library now, I ping you in a few minutes.

**Comment by jerabaul29** [comment]
@jvoermans I pushed now. A few comments:

- you can already see from the debug information the information you need: unit is inH2, whatever that means...
- I think the issue is that this piece of matching code seems to be a bit broken: https://github.com/jerabaul29/Honeywell_RSC/blob/f42140ac3be55a5ae70471f8665dd040737fd57a/src/Honeywell_RSC.cpp#L136-L162
- a possible workaround may be to just copy "stupidly" the content of the EEPROM data and use this rather than the piece of string matching logics: https://github.com/jerabaul29/Honeywell_RSC/blob/f42140ac3be55a5ae70471f8665dd040737fd57a/src/Honeywell_RSC.cpp#L131-L134

So you may try the code with:

- 1 : comment out https://github.com/jerabaul29/Honeywell_RSC/blob/f42140ac3be55a5ae70471f8665dd040737fd57a/src/Honeywell_RSC.cpp#L131-L134 and keep https://github.com/jerabaul29/Honeywell_RSC/blob/f42140ac3be55a5ae70471f8665dd040737fd57a/src/Honeywell_RSC.cpp#L136-L162
- 2: keep https://github.com/jerabaul29/Honeywell_RSC/blob/f42140ac3be55a5ae70471f8665dd040737fd57a/src/Honeywell_RSC.cpp#L131-L134 and comment out https://github.com/jerabaul29/Honeywell_RSC/blob/f42140ac3be55a5ae70471f8665dd040737fd57a/src/Honeywell_RSC.cpp#L136-L162

and use what you like best in the future :) .

**Comment by jvoermans** [comment]
That make sense. It's 'inch H2O', that is consistent with the datasheet. Many thanks for your help!
